config {
  type: "view",
  schema: "prod_logic_ar_jinji_basic",
  name: "logic_preprocessing_jinji_basic_data_parttime",
  description: "非職基本台帳の前処理（個別データ対応）",
  tags: [constants.CATEGORY_TAG.jinji, constants.CATEGORY_TAG.work_product],
  bigquery: {
    labels:{
      "df_repository": "ws_shared_jinji-basic",
      "step": constants.CATEGORY_STEP.logic,
      "use": constants.CATEGORY_USE_CONTENTS.ar
    }
  }
}

js {
 const target_date = constants.SQL_PARAMETER.target_date;    
}

SELECT
  -- 加工後に置き換える項目以外をすべて抽出
  t1.* EXCEPT (shokuin_mei_code, shokuin_mei, bukyoku_code, bukyoku_mei),
  case
  when t1.shokuin_bangou IN ("CD163A78277C5B33C807A9696A03DC526960D29AC7D7A4DE1D79648ECF072E65","C2E55C0927707E36F5B4061911AE792B217CF95330E1D890DE303DC70EECC2D5","9A8E26B06AE33AD5AEC913328AC7C8E4F1F54B0C9B93DA7E8C14DCC83AF496A4")
    and t1.renkei_kijunbi = "2010-05-01" then "810"
  else t1.shokuin_mei_code
  end as shokuin_mei_code,
  case
  when t1.shokuin_bangou IN ("CD163A78277C5B33C807A9696A03DC526960D29AC7D7A4DE1D79648ECF072E65","C2E55C0927707E36F5B4061911AE792B217CF95330E1D890DE303DC70EECC2D5","9A8E26B06AE33AD5AEC913328AC7C8E4F1F54B0C9B93DA7E8C14DCC83AF496A4")
    and t1.renkei_kijunbi = "2010-05-01" then "学外非常勤講師"
  else t1.shokuin_mei
  end as shokuin_mei,

  case
  when t1.shokuin_bangou = "C2E55C0927707E36F5B4061911AE792B217CF95330E1D890DE303DC70EECC2D5"
    and t1.renkei_kijunbi = "2010-05-01" then "510000"
  else t1.bukyoku_code
  end as bukyoku_code,
  case
  when t1.shokuin_bangou = "C2E55C0927707E36F5B4061911AE792B217CF95330E1D890DE303DC70EECC2D5"
    and t1.renkei_kijunbi = "2010-05-01" then "総合人間学部"
  else t1.bukyoku_mei
  end as bukyoku_mei,
FROM
  ${ref("hishoku_kihon_daichou")} AS t1